LOGDIR: '/data1/bsanthanam/thesis/data/logs/'
# PATH: '/media/federico/federico_hdd/shape_completion/SweetPepper/SweetPepper'
# PATH: '/export/data/federico-domain-adapatation/Strawberry/Strawberry'
#PATH: '/data1/bsanthanam/thesis/data/sample_dataset_rodrigo/SweetPepperSmall'
PATH: '/data1/bsanthanam/thesis/data/sweet_pepper_RGBfeats_subset'
# PATH: '/data1/bsanthanam/thesis/data/sample_dataset_Rodrigo_p72/'

#uncomment for testing just 5 images
# PATH: '/data1/bsanthanam/thesis/data/sweet_pepper_RGBfeats_test_data'
#PATH: '/data1/bsanthanam/thesis/data/sweet_pepper_master_copy/sunburned_peppers_train_trial'

# PATH: '/home/bharath/Desktop/thesis/code/data/sweet_pepper_master_copy/damaged_peppers_copy'
# PATH: '/export/data/federico-domain-adapatation/SweetPepper/SweetPepper'
EXPERIMENT:
    ID: sunburned_pepper_withoutRGB_14_09_layer6
TRAIN:
    AUG: true
    BATCH_ACC: 4
    BATCH_SIZE: 1
    DECAY: 0.95
    FREEZE_MODULES: []
    LR: 0.0001
    MAX_EPOCH: 20
    NUM_WORKERS: 0
    N_GPUS: -1
    STEP: 50
MODEL:    
    DATASET: FRUITS
    OVERFIT: False
    FRUIT: SWEETPEPPER
    SMOOTH_SW: 1
    SMOOTH_ST: 10

LOSS:
    WEIGHTS_KEYS: ['loss_ce','loss_dice','loss_mask']
    WEIGHTS: [2.0, 5.0, 5.0]
    MASK_W: [0.15,0.25,0.5]
    EOS_COEF: 0.1
    NUM_POINTS: 50000 #n of points to sample for the loss
    NUM_MASK_PTS: 500 #points to sample within each mask
    P_RATIO: 0.4 #ratio of points to use for the loss
    # auxiliary semantic loss
    SEM:
        WEIGHTS: [2,6] #Ce, Lovasz

FRUITS:
    NUM_CLASSES: 0
    TEMPLATE_DIM: 3
    SENSOR: 'realsense'
    AUGMENTATION: False

LEAVES:
    NUM_CLASSES: 0
    TEMPLATE_DIM: 2
